# Generated by Django 4.2.5 on 2023-12-05 03:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scheduler', '0003_alter_appointment_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomReservation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_ts', models.DateTimeField()),
                ('end_ts', models.DateTimeField()),
                ('medico', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='medico_room_reservations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('room_reservations', models.ManyToManyField(to='scheduler.roomreservation')),
            ],
        ),
    ]
