# Generated by Django 4.2.5 on 2023-12-06 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_roomreservation_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_reservations',
            field=models.ManyToManyField(default=None, to='scheduler.roomreservation'),
        ),
    ]
