# Generated by Django 4.2.5 on 2023-12-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0002_appuser_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='is_doctor',
            field=models.BooleanField(default=False),
        ),
    ]
