# Generated by Django 4.2.5 on 2023-09-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remedios', models.CharField(max_length=200)),
                ('medico', models.CharField(max_length=200)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('observacoes', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
