# Generated by Django 4.2.5 on 2023-09-16 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('max_capacity', models.PositiveIntegerField()),
                ('current_capacity', models.PositiveIntegerField(default=0)),
                ('location', models.CharField(max_length=255)),
                ('hospital_or_clinic_name', models.CharField(max_length=255)),
                ('medic_name', models.CharField(max_length=255)),
            ],
        ),
    ]
