# Generated by Django 4.2.5 on 2023-11-23 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='end_time',
            new_name='end_ts',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='start_time',
            new_name='start_ts',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='current_capacity',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='hospital_or_clinic_name',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='location',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='max_capacity',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='medic_name',
        ),
        migrations.AddField(
            model_name='appointment',
            name='medico',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='medico_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='paciente',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paciente_appointments', to=settings.AUTH_USER_MODEL),
        ),
    ]
